### ISSUE TITLE
Mimicry Panic

### ISSUE THREAD

**Issue by samcm** [ethpandaops/xatu#306]
fatal error: concurrent map read and map write

goroutine 3634334 [running]:
github.com/ethpandaops/ethcore/pkg/execution/mimicry.(*Client).handlePooledTransactions(0xc000391980, {0x1c05ae0, 0x28ff880}, 0x2896600?, {0xc0136fa000, 0xb, 0x160780})
	/home/runner/go/pkg/mod/github.com/ethpandaops/ethcore@v0.0.0-20240306031202-16f9e1926c0c/pkg/execution/mimicry/message_pooled_transactions.go:39 +0x105
github.com/ethpandaops/ethcore/pkg/execution/mimicry.(*Client).startSession(0xc000391980, {0x1c05ae0, 0x28ff880})
	/home/runner/go/pkg/mod/github.com/ethpandaops/ethcore@v0.0.0-20240306031202-16f9e1926c0c/pkg/execution/mimicry/client.go:233 +0x277
github.com/ethpandaops/ethcore/pkg/execution/mimicry.(*Client).Start.func1()
	/home/runner/go/pkg/mod/github.com/ethpandaops/ethcore@v0.0.0-20240306031202-16f9e1926c0c/pkg/execution/mimicry/client.go:116 +0x1f
created by github.com/ethpandaops/ethcore/pkg/execution/mimicry.(*Client).Start in goroutine 108748
	/home/runner/go/pkg/mod/github.com/ethpandaops/ethcore@v0.0.0-20240306031202-16f9e1926c0c/pkg/execution/mimicry/client.go:115 +0x80b

**Comment by samcm** [comment]
https://github.com/ethpandaops/ethcore/pull/23
